version: '3'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/usr/src/app/src
  server:
    container_name: server
    build: ./server
    volumes:
      - ./server/src:/usr/src/app/src
    ports:
      - '4444:4444'
    restart: always
    depends_on:
      - mongodb
    env_file:
      - ./server/.env
  mongodb:
    image: mongo:latest
    restart: on-failure
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - 27018:27017
