version: '3'

services:
  main:
    container_name: main
    build: .
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '4444:4444'
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
  mongodb:
    image: mongo:latest
    restart: on-failure
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - 27018:27017
